<nav>
		<ul>
			<li><a href="index.php"> The Team </a></li>
			<li>Maisha
				<ul>
					<li><a href="maishacourses.php">Courses</a></li>
					<li><a href="maishaextra.php">Extra-Curriculars</a></li>
					<li><a href="maishahobbies.php">Hobbies</a></li>
				</ul>
			</li>
			<li>Sharon
				<ul>
					<li><a href="sharoncourses.php">Courses</a></li>
					<li><a href="sharonextra.php">Extra-Curriculars</a></li>
					<li><a href="sharonhobbies.php">Hobbies</a></li>
				</ul>
			</li>
			<li>Chadia
				<ul>
					<li><a href="chadiacourses.php">Courses</a></li>
					<li><a href="chadiaextra.php">Extra-Curriculars</a></li>
					<li><a href="chadiahobbies.php">Hobbies</a></li>
				</ul>
			</li>
		</ul>
</nav>