<nav>
		<ul class="navul">
			<li class="home"><a href="index.php"> The Team </a></li>
			<li class="dropdown">
				<a href="javascript:void(0)" class="droptitle">Maisha</a>
				<div class="droplist">
					<a href="maishacourses.php">Courses</a>
					<a href="maishaextra.php">Extra-Curriculars</a>
					<a href="maishahobbies.php">Hobbies</a>
				</div>
			</li>
			<li class="dropdown">
				<a href="javascript:void(0)" class="droptitle">Sharon</a>
				<div class="droplist"> 
					<a href="sharoncourses.php">Courses</a>
					<a href="sharonextra.php">Extra-Curriculars</a>
					<a href="sharonhobbies.php">Hobbies</a>
				</div>
			</li>
			<li class="dropdown">
			<a href="javascript:void(0)" class="droptitle">Chadia</a>
				<div class="droplist">
					<a href="chadiacourses.php">Courses</a>
					<a href="chadiaextra.php">Extra-Curriculars</a>
					<a href="chadiahobbies.php">Hobbies</a>
				</div>
			</li>
		</ul>
</nav>

